version: '3'
services:
  discovery:
    image: ms-discovery:v1
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - proxy
    ports:
      - 8761:8761
  config:
    image: ms-config:v1
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - proxy
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - discovery
    ports:
      - 8888:8888
  school-service:
    image: ms-school-service:v1
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - proxy
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 9000-9005:9000
  school-ui:
    image: ms-school-ui:v1
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - local_proxy
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.profiles.active=production
    restart: on-failure
    depends_on:
      - discovery
      - config
    ports:
      - 8080:8080
# Networks to be created to facilitate communication between containers
networks:
  proxy:
    driver: overlay